Repository likeness-pop/livelike, pull requests merged in 2025-05, with the labels that each got.

#63 Add support for synthetic population attribution
  livelike/__init__.py
  livelike/_attribution.py
  livelike/attribution.py
  livelike/config.py
  livelike/tests/attribution_eval_data/eval_data_household.parquet
  livelike/tests/attribution_eval_data/eval_data_person.parquet
  livelike/tests/test_attribution.py
Labels: enhancement, population

#65 Add small-area estimation module
  livelike/__init__.py
  livelike/sae.py
Labels: enhancement

#73 Update typehints/docs
  livelike/_attribution.py
  livelike/sae.py
Labels: documentation, maint

#79 remove import of `pymedm` in `sae.py`
  livelike/attribution.py
  livelike/multi.py
  livelike/sae.py
Labels: documentation, deps/reqs

#81 Add support for summarizing ensemble small-area estimates
  livelike/__init__.py
  livelike/sae.py
Labels: enhancement
