Repository likeness-pop/livelike, pull requests merged in 2025-03, with the labels that each got.

#3 minimal jax pin -- #2
  .ci/py311_livelike_latest.yml
  .ci/py311_livelike_min.yml
  .ci/py312_livelike_dev.yml
  .ci/py312_livelike_latest.yml
  pyproject.toml
Labels: deps/reqs

#5 Update pums.edu_attainment()
  livelike/pums.py
  livelike/tests/test_pums.py
Labels: constraints

#8 initial setup of CI, etc.
  .ci/py311_livelike_latest.yaml
  .ci/py311_livelike_min.yaml
  .ci/py312_livelike_dev.yaml
  .ci/py312_livelike_latest.yaml
  .github/workflows/continuous_integration.yml
  .gitlab-ci.yml
  .pre-commit-config.yaml
  README.md
  codecov.yml
  livelike/acs.py
  livelike/config.py
  livelike/pums.py
  livelike/tests/conftest.py
  livelike/tests/test_pums.py
  livelike_acs_cache/temp.txt
  pyproject.toml
Labels: CI/testing, infra

#43 streamline dependency stipulations [2025-03-30]
  pyproject.toml
Labels: deps/reqs

#45 prep `v1.4.8` - merge `develop` into `main`
  .ci/py311_livelike_latest.yaml
  .ci/py311_livelike_min.yaml
  .ci/py312_livelike_dev.yaml
  .ci/py312_livelike_latest.yaml
  .github/workflows/continuous_integration.yml
  .gitlab-ci.yml
  .pre-commit-config.yaml
  README.md
  codecov.yml
  livelike/acs.py
  livelike/config.py
  livelike/pums.py
  livelike/tests/conftest.py
  livelike/tests/test_pums.py
  livelike_acs_cache/temp.txt
  pyproject.toml
Labels: tag/release
